/// Flutter icons Pokeicons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pokeicons
///      fonts:
///       - asset: fonts/Pokeicons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Pokeicons {
  Pokeicons._();

  static const _kFontFam = 'Pokeicons';
  static const String? _kFontPkg = null;

  static const IconData pikachu = IconData(0xe800,
      fontFamily: _kFontFam, fontPackage: _kFontPkg); //pikachu icon
  static const IconData pokedex = IconData(0xe801,
      fontFamily: _kFontFam, fontPackage: _kFontPkg); //pokédex icon
  static const IconData pokehat = IconData(0xe802,
      fontFamily: _kFontFam, fontPackage: _kFontPkg); //hat pokémon trainer icon

  //Custom icons used in BottomNavigationBar, created with www.fluttericon.com
}
