//The Egg model and entity
import 'package:floor/floor.dart';

@entity //Egg is a class that defines an entity (table structure fields)
class Egg{
  @PrimaryKey(autoGenerate: true)
  final int? idtable; //idtable will be the primary key of the table
                      //nullable since it's autogenerated

  final int id;
  final String name;
  final int hatchcounter;
  bool openegg;

  Egg({
    required this.idtable,
    required this.id,
    required this.name,
    required this.hatchcounter,
    required this.openegg,
  });

  //This factory method is used to create a new Egg object from a JSON.
  factory Egg.fromJson(Map<String, dynamic> json) {
    return Egg(
      idtable: null,

      id: json['id'],
      name: json['name'],
      hatchcounter: json['hatch_counter'],

      openegg: false,
    );
  }//Egg.fromJson

  //Encode to JSON
  Map <String, dynamic> toJson() => {
    'idtable': idtable,

    'id': id,
    'name': name,
    'hatch_counter': hatchcounter,
    
    'openegg': openegg,
  };
  
}//Egg